using MinecraftMappings.Internal;
using MinecraftMappings.Internal.Entities;
using MinecraftMappings.Internal.Models;

namespace MinecraftMappings.Minecraft.Java.Entities
{
    public class Witch : JavaEntityData
    {
        public const string EntityId = "witch";
        public const string EntityName = "Witch";


        public Witch() : base(EntityName)
        {
            Versions.Add(new JavaEntityDataVersion {
                Id = EntityId,
                TextVersion = "1.4.2",
            });

            Versions.Add(new JavaEntityDataVersion {
                Id = EntityId,
                TextVersion = "1.14",
                UVMappings = {
                    new UVRegion {
                        Name = "Head-Up",
                        Left = 8 /64d,
                        Top = 0,
                        Width = 8 /64d,
                        Height = 8 /128d,
                    },
                    new UVRegion {
                        Name = "Head-Down",
                        Left = 16 /64d,
                        Top = 0,
                        Width = 8 /64d,
                        Height = 8 /128d,
                    },
                    new UVRegion {
                        Name = "Head-East",
                        Left = 0,
                        Top = 8 /128d,
                        Width = 8 /64d,
                        Height = 10 /128d,
                    },
                    new UVRegion {
                        Name = "Head-North",
                        Left = 8 /64d,
                        Top = 8 /128d,
                        Width = 8 /64d,
                        Height = 10 /128d,
                    },
                    new UVRegion {
                        Name = "Head-West",
                        Left = 16 /64d,
                        Top = 8 /128d,
                        Width = 8 /64d,
                        Height = 10 /128d,
                    },
                    new UVRegion {
                        Name = "Head-South",
                        Left = 24 /64d,
                        Top = 8 /128d,
                        Width = 8 /64d,
                        Height = 10 /128d,
                    },

                    new UVRegion {
                        Name = "Nose-Up",
                        Left = 26 /64d,
                        Top = 0,
                        Width = 2 /64d,
                        Height = 2 /128d,
                    },
                    new UVRegion {
                        Name = "Nose-Down",
                        Left = 28 /64d,
                        Top = 0,
                        Width = 2 /64d,
                        Height = 2 /128d,
                    },
                    new UVRegion {
                        Name = "Nose-East",
                        Left = 24 /64d,
                        Top = 2 /128d,
                        Width = 2 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "Nose-North",
                        Left = 26 /64d,
                        Top = 2 /128d,
                        Width = 2 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "Nose-West",
                        Left = 28 /64d,
                        Top = 2 /128d,
                        Width = 2 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "Nose-South",
                        Left = 30 /64d,
                        Top = 2 /128d,
                        Width = 2 /64d,
                        Height = 4 /128d,
                    },

                    new UVRegion {
                        Name = "Mole-Up",
                        Left = 1 /64d,
                        Top = 0,
                        Width = 1 /64d,
                        Height = 1 /128d,
                    },
                    new UVRegion {
                        Name = "Mole-Down",
                        Left = 2 /64d,
                        Top = 0,
                        Width = 1 /64d,
                        Height = 1 /128d,
                    },
                    new UVRegion {
                        Name = "Mole-East",
                        Left = 0,
                        Top = 1 /128d,
                        Width = 1 /64d,
                        Height = 1 /128d,
                    },
                    new UVRegion {
                        Name = "Mole-North",
                        Left = 1 /64d,
                        Top = 1 /128d,
                        Width = 1 /64d,
                        Height = 1 /128d,
                    },
                    new UVRegion {
                        Name = "Mole-West",
                        Left = 2 /64d,
                        Top = 1 /128d,
                        Width = 1 /64d,
                        Height = 1 /128d,
                    },
                    new UVRegion {
                        Name = "Mole-South",
                        Left = 3 /64d,
                        Top = 1 /128d,
                        Width = 1 /64d,
                        Height = 1 /128d,
                    },

                    new UVRegion {
                        Name = "Body-Up",
                        Left = 22 /64d,
                        Top = 20 /128d,
                        Width = 8 /64d,
                        Height = 6 /128d,
                    },
                    new UVRegion {
                        Name = "Body-Down",
                        Left = 30 /64d,
                        Top = 20 /128d,
                        Width = 8 /64d,
                        Height = 6 /128d,
                    },
                    new UVRegion {
                        Name = "Body-East",
                        Left = 16 /64d,
                        Top = 26 /128d,
                        Width = 6 /64d,
                        Height = 12 /128d,
                    },
                    new UVRegion {
                        Name = "Body-North",
                        Left = 22 /64d,
                        Top = 26 /128d,
                        Width = 8 /64d,
                        Height = 12 /128d,
                    },
                    new UVRegion {
                        Name = "Body-West",
                        Left = 30 /64d,
                        Top = 26 /128d,
                        Width = 6 /64d,
                        Height = 12 /128d,
                    },
                    new UVRegion {
                        Name = "Body-South",
                        Left = 36 /64d,
                        Top = 26 /128d,
                        Width = 8 /64d,
                        Height = 12 /128d,
                    },

                    new UVRegion {
                        Name = "BodyWear-Up",
                        Left = 6 /64d,
                        Top = 38 /128d,
                        Width = 8 /64d,
                        Height = 6 /128d,
                    },
                    new UVRegion {
                        Name = "BodyWear-Down",
                        Left = 14 /64d,
                        Top = 38 /128d,
                        Width = 8 /64d,
                        Height = 6 /128d,
                    },
                    new UVRegion {
                        Name = "BodyWear-East",
                        Left = 0,
                        Top = 44 /128d,
                        Width = 6 /64d,
                        Height = 18 /128d,
                    },
                    new UVRegion {
                        Name = "BodyWear-North",
                        Left = 6 /64d,
                        Top = 44 /128d,
                        Width = 8 /64d,
                        Height = 18 /128d,
                    },
                    new UVRegion {
                        Name = "BodyWear-West",
                        Left = 14 /64d,
                        Top = 44 /128d,
                        Width = 6 /64d,
                        Height = 18 /128d,
                    },
                    new UVRegion {
                        Name = "BodyWear-South",
                        Left = 20 /64d,
                        Top = 44 /128d,
                        Width = 8 /64d,
                        Height = 18 /128d,
                    },

                    new UVRegion {
                        Name = "Legs-Up",
                        Left = 4 /64d,
                        Top = 22 /128d,
                        Width = 4 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "Legs-Down",
                        Left = 8 /64d,
                        Top = 22 /128d,
                        Width = 4 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "Legs-East",
                        Left = 0,
                        Top = 26 /128d,
                        Width = 4 /64d,
                        Height = 12 /128d,
                    },
                    new UVRegion {
                        Name = "Legs-North",
                        Left = 4 /64d,
                        Top = 26 /128d,
                        Width = 4 /64d,
                        Height = 12 /128d,
                    },
                    new UVRegion {
                        Name = "Legs-West",
                        Left = 8 /64d,
                        Top = 26 /128d,
                        Width = 4 /64d,
                        Height = 12 /128d,
                    },
                    new UVRegion {
                        Name = "Legs-South",
                        Left = 12 /64d,
                        Top = 26 /128d,
                        Width = 4 /64d,
                        Height = 12 /128d,
                    },

                    new UVRegion {
                        Name = "Arms1-Up",
                        Left = 48 /64d,
                        Top = 22 /128d,
                        Width = 4 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "Arms1-Down",
                        Left = 52 /64d,
                        Top = 22 /128d,
                        Width = 4 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "Arms1-East",
                        Left = 44 /64d,
                        Top = 26 /128d,
                        Width = 4 /64d,
                        Height = 8 /128d,
                    },
                    new UVRegion {
                        Name = "Arms1-North",
                        Left = 48 /64d,
                        Top = 26 /128d,
                        Width = 4 /64d,
                        Height = 8 /128d,
                    },
                    new UVRegion {
                        Name = "Arms1-West",
                        Left = 52 /64d,
                        Top = 26 /128d,
                        Width = 4 /64d,
                        Height = 8 /128d,
                    },
                    new UVRegion {
                        Name = "Arms1-South",
                        Left = 56 /64d,
                        Top = 26 /128d,
                        Width = 4 /64d,
                        Height = 8 /128d,
                    },

                    new UVRegion {
                        Name = "Arms2-Up",
                        Left = 44 /64d,
                        Top = 38 /128d,
                        Width = 8 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "Arms2-Down",
                        Left = 52 /64d,
                        Top = 38 /128d,
                        Width = 8 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "Arms2-East",
                        Left = 40 /64d,
                        Top = 42 /128d,
                        Width = 4 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "Arms2-North",
                        Left = 44 /64d,
                        Top = 42 /128d,
                        Width = 8 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "Arms2-West",
                        Left = 52 /64d,
                        Top = 42 /128d,
                        Width = 4 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "Arms2-South",
                        Left = 56 /64d,
                        Top = 42 /128d,
                        Width = 8 /64d,
                        Height = 4 /128d,
                    },

                    new UVRegion {
                        Name = "HeadWear1-Up",
                        Left = 10 /64d,
                        Top = 64 /128d,
                        Width = 10 /64d,
                        Height = 10 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear1-Down",
                        Left = 20 /64d,
                        Top = 64 /128d,
                        Width = 10 /64d,
                        Height = 10 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear1-East",
                        Left = 0 /64d,
                        Top = 74 /128d,
                        Width = 10 /64d,
                        Height = 2 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear1-North",
                        Left = 10 /64d,
                        Top = 74 /128d,
                        Width = 10 /64d,
                        Height = 2 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear1-West",
                        Left = 20 /64d,
                        Top = 74 /128d,
                        Width = 10 /64d,
                        Height = 2 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear1-South",
                        Left = 30 /64d,
                        Top = 74 /128d,
                        Width = 10 /64d,
                        Height = 2 /128d,
                    },

                    new UVRegion {
                        Name = "HeadWear2-Up",
                        Left = 7 /64d,
                        Top = 76 /128d,
                        Width = 7 /64d,
                        Height = 7 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear2-Down",
                        Left = 14 /64d,
                        Top = 76 /128d,
                        Width = 7 /64d,
                        Height = 7 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear2-East",
                        Left = 0 /64d,
                        Top = 83 /128d,
                        Width = 7 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear2-North",
                        Left = 7 /64d,
                        Top = 83 /128d,
                        Width = 7 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear2-West",
                        Left = 14 /64d,
                        Top = 83 /128d,
                        Width = 7 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear2-South",
                        Left = 21 /64d,
                        Top = 83 /128d,
                        Width = 7 /64d,
                        Height = 4 /128d,
                    },

                    new UVRegion {
                        Name = "HeadWear3-Up",
                        Left = 4 /64d,
                        Top = 87 /128d,
                        Width = 4 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear3-Down",
                        Left = 8 /64d,
                        Top = 87 /128d,
                        Width = 4 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear3-East",
                        Left = 0 /64d,
                        Top = 91 /128d,
                        Width = 4 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear3-North",
                        Left = 4 /64d,
                        Top = 91 /128d,
                        Width = 4 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear3-West",
                        Left = 8 /64d,
                        Top = 91 /128d,
                        Width = 4 /64d,
                        Height = 4 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear3-South",
                        Left = 12 /64d,
                        Top = 91 /128d,
                        Width = 4 /64d,
                        Height = 4 /128d,
                    },

                    new UVRegion {
                        Name = "HeadWear4-Up",
                        Left = 1 /64d,
                        Top = 95 /128d,
                        Width = 1 /64d,
                        Height = 1 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear4-Down",
                        Left = 2 /64d,
                        Top = 95 /128d,
                        Width = 1 /64d,
                        Height = 1 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear4-East",
                        Left = 0 /64d,
                        Top = 96 /128d,
                        Width = 1 /64d,
                        Height = 2 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear4-North",
                        Left = 1 /64d,
                        Top = 96 /128d,
                        Width = 1 /64d,
                        Height = 2 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear4-West",
                        Left = 2 /64d,
                        Top = 96 /128d,
                        Width = 1 /64d,
                        Height = 2 /128d,
                    },
                    new UVRegion {
                        Name = "HeadWear4-South",
                        Left = 3 /64d,
                        Top = 96 /128d,
                        Width = 1 /64d,
                        Height = 2 /128d,
                    },
                },
            });
        }
    }
}
