using PixelGraph.Common.ResourcePack;
using PixelGraph.Common.Textures;

namespace PixelGraph.Common.TextureFormats.Java
{
    public class LabPbr12Format : ITextureFormatFactory
    {
        public const string Description = "The second LabPBR standard.";


        public TextureMappingCollection Create()
        {
            return new TextureMappingCollection {
                new() {
                    Name = (p, m) => m.Name,
                    Tag = TextureTags.Color,
                    Channels = {
                        new ChannelMapping {
                            Type = EncodingChannel.ColorRed,
                            Color = ColorChannel.Red,
                            MinValue = 0m,
                            MaxValue = 255m,
                            RangeMin = 0,
                            RangeMax = 255,
                            Shift = 0,
                            Power = 1m,
                            Invert = false,
                        },
                        new ChannelMapping {
                            Type = EncodingChannel.ColorGreen,
                            Color = ColorChannel.Green,
                            MinValue = 0m,
                            MaxValue = 255m,
                            RangeMin = 0,
                            RangeMax = 255,
                            Shift = 0,
                            Power = 1m,
                            Invert = false,
                        },
                        new ChannelMapping {
                            Type = EncodingChannel.ColorBlue,
                            Color = ColorChannel.Blue,
                            MinValue = 0m,
                            MaxValue = 255m,
                            RangeMin = 0,
                            RangeMax = 255,
                            Shift = 0,
                            Power = 1m,
                            Invert = false,
                        },
                        new ChannelMapping {
                            Type = EncodingChannel.Opacity,
                            Color = ColorChannel.Alpha,
                            MinValue = 0m,
                            MaxValue = 255m,
                            RangeMin = 0,
                            RangeMax = 255,
                            Shift = 0,
                            Power = 1m,
                            Invert = false,
                            DefaultValue = 255,
                        },
                    },
                },
                new() {
                    Name = (p, m) => $"{m.Name}_n",
                    Tag = TextureTags.Normal,
                    Channels = {
                        new ChannelMapping {
                            Type = EncodingChannel.NormalX,
                            Color = ColorChannel.Red,
                            MinValue = 0m,
                            MaxValue = 1m,
                            RangeMin = 0,
                            RangeMax = 255,
                            Shift = 0,
                            Power = 1m,
                            Invert = false,
                        },
                        new ChannelMapping {
                            Type = EncodingChannel.NormalY,
                            Color = ColorChannel.Green,
                            MinValue = 0m,
                            MaxValue = 1m,
                            RangeMin = 0,
                            RangeMax = 255,
                            Shift = 0,
                            Power = 1m,
                            Invert = false,
                        },
                        new ChannelMapping {
                            Type = EncodingChannel.Occlusion,
                            Color = ColorChannel.Blue,
                            MinValue = 0m,
                            MaxValue = 1m,
                            RangeMin = 0,
                            RangeMax = 255,
                            Shift = 0,
                            Power = 1m,
                            Invert = true,
                        },
                        new ChannelMapping {
                            Type = EncodingChannel.Height,
                            Color = ColorChannel.Alpha,
                            MinValue = 0m,
                            MaxValue = 1m,
                            RangeMin = 0,
                            RangeMax = 255,
                            Shift = 0,
                            Power = 1m,
                            Invert = true,
                        },
                    },
                },
                new() {
                    Name = (p, m) => $"{m.Name}_s",
                    Tag = TextureTags.Specular,
                    Channels = {
                        new ChannelMapping {
                            Type = EncodingChannel.Smooth,
                            Color = ColorChannel.Red,
                            MinValue = 0m,
                            MaxValue = 1m,
                            RangeMin = 0,
                            RangeMax = 255,
                            Shift = 0,
                            Power = 1m,
                            Invert = false,
                        },
                        new ChannelMapping {
                            Type = EncodingChannel.F0,
                            Color = ColorChannel.Green,
                            MinValue = 0m,
                            MaxValue = 0.9m,
                            RangeMin = 0,
                            RangeMax = 229,
                            Shift = 0,
                            Power = 0.5m,
                            Invert = false,
                        },
                        new ChannelMapping {
                            Type = EncodingChannel.Metal,
                            Color = ColorChannel.Green,
                            Sampler = Samplers.Samplers.Nearest,
                            MinValue = 230m,
                            MaxValue = 255m,
                            RangeMin = 230,
                            RangeMax = 255,
                            Shift = 0,
                            Power = 1m,
                            Invert = false,
                        },
                        new ChannelMapping {
                            Type = EncodingChannel.Porosity,
                            Color = ColorChannel.Blue,
                            MinValue = 0m,
                            MaxValue = 1m,
                            RangeMin = 0,
                            RangeMax = 64,
                            Shift = 0,
                            Power = 1m,
                            Invert = false,
                        },
                        new ChannelMapping {
                            Type = EncodingChannel.SubSurfaceScattering,
                            Color = ColorChannel.Blue,
                            MinValue = 0m,
                            MaxValue = 1m,
                            RangeMin = 65,
                            RangeMax = 255,
                            Shift = 0,
                            Power = 1m,
                            Invert = false,
                        },
                        new ChannelMapping {
                            Type = EncodingChannel.Emissive,
                            Color = ColorChannel.Alpha,
                            MinValue = 0m,
                            MaxValue = 1m,
                            RangeMin = 0,
                            RangeMax = 255,
                            Shift = -1,
                            Power = 1m,
                            Invert = false,
                        },
                    },
                },
            };
        }
    }
}
